Archimedes' Ships - Mekanism
/*Poorly created by Padfoote
Enjoy the nerfs */
##Archimedes Ships
val shipHelm = <ArchimedesShips:marker>;
val floater = <ArchimedesShips:floater>;
val arcBalloonWhite = <ArchimedesShips:balloon>;
val arcBalloonOrange = <ArchimedesShips:balloon:1>;
val arcBalloonMagenta = <ArchimedesShips:balloon:2>;
val arcBalloonBlueLight = <ArchimedesShips:balloon:3>;
val arcBalloonYellow = <ArchimedesShips:balloon:4>;
val arcBalloonLime = <ArchimedesShips:balloon:5>;
val arcBalloonPink = <ArchimedesShips:balloon:6>;
val arcBalloonGray = <ArchimedesShips:balloon:7>;
val arcBalloonSilver = <ArchimedesShips:balloon:8>;
val arcBalloonCyan = <ArchimedesShips:balloon:9>;
val arcBalloonPurple = <ArchimedesShips:balloon:10>;
val arcBalloonBlue = <ArchimedesShips:balloon:11>;
val arcBalloonBrown = <ArchimedesShips:balloon:12>;
val arcBalloonGreen = <ArchimedesShips:balloon:13>;
val arcBalloonRed = <ArchimedesShips:balloon:14>;
val arcBalloonBlack = <ArchimedesShips:balloon:15>;
val gaugeBasic = <ArchimedesShips:gauge>;
val gaugeAdvanced = <ArchimedesShips:gauge:1>;
val seatPassenger = <ArchimedesShips:seat>;
val bufferShore = <ArchimedesShips:buffer>;
val engineSteam = <ArchimedesShips:engine>;
val crateWood = <ArchimedesShips:crate_wood>;
val allArcBalloons = <<ArchimedesShips:balloon:*>;

##Mekanism
val armoredJetpack = <Mekanism:ArmoredJetpack>;
val atomicDisassembler = <Mekanism:AtomicDisassembler>;
val MekBalloonBlack = <Mekanism:Balloon>;
val MekBalloonRed = <Mekanism:Balloon:1>;
val MekBalloonGreen = <Mekanism:Balloon:2>;
val MekBalloonBrown = <Mekanism:Balloon:3>;
val MekBalloonBlue = <Mekanism:Balloon:4>;
val MekBalloonPurple = <Mekanism:Balloon:5>;
val MekBalloonCyan = <Mekanism:Balloon:6>;
val MekBalloonGreyLight = <Mekanism:Balloon:7>;
val MekBalloonGrey = <Mekanism:Balloon:8>;
val MekBalloonPink = <Mekanism:Balloon:9>;
val MekBalloonLime = <Mekanism:Balloon:10>;
val MekBalloonYellow = <Mekanism:Balloon:11>;
val MekBalloonBlueLight = <Mekanism:Balloon:12>;
val MekBalloonMagenta = <Mekanism:Balloon:13>;
val MekBalloonOrange = <Mekanism:Balloon:14>;
val MekBalloonWhite = <Mekanism:Balloon:15>;
val allMekBalloons = <Mekanism:Balloon:*>;
val osmiumBlock = <Mekanism:BasicBlock>;
val salinationBlock = <Mekanism:BasicBlock2>;
val mekBiofuel = <Mekanism:BioFuel>;
val boundingBlock = <Mekanism:BoundingBlock>;
val brineBucket = <Mekanism:BrineBucket>;
val cardboardBox = <Mekanism:CardboardBox>;
val oreClump = <Mekanism:Clump>;
val compressedCarbon = <Mekanism:CompressedCarbon>;
val compressedDiamond = <Mekanism:CompressedDiamond>;
val compressedObsidian = <Mekanism:CompressedObsidian>;
val compressedRedstone = <Mekanism:CompressedRedstone>;
val configurator = <Mekanism:Configurator>;
val controlCircuit = <Mekanism:ControlCircuit>;
val controlCircuitAdv = <Mekanism:ControlCircuit:1>;
val controlCircuitElite = <Mekanism:ControlCircuit:2>;
val controlCircuitUltimate = <Mekanism:ControlCircuit:3>;
val controlCircuitAll = <Mekanism:ControlCircuit:*>;
val oreCrystal = <Mekanism:Crystal>;
val dictionary = <Mekanism:Dictionary>;
val oreDirtyDust = <Mekanism:DirtyDust>;
val oreDust = <Mekanism:Dust>;
val electricBow = <Mekanism:ElectricBow>;
val electrolyticCore = <Mekanism:ElectrolyticCore>;
val energyCube = <Mekanism:EnergyCube>;
val energyTablet = <Mekanism:EnergyTablet>;
val energyUpgrade = <Mekanism:EnergyUpgrade>;
val enrichedAlloy = <Mekanism:EnrichedAlloy>;
val enrichedIron = <Mekanism:EnrichedIron>;
val filterCard = <Mekanism:FilterCard>;
val frictionBoots = <Mekanism:FrictionBoots>;
val gasMask = <Mekanism:GasMask>;
val gasTank = <Mekanism:GasTank>;
val glowPanel = <Mekanism:GlowPanel>;
val glowPlasticBlock = <Mekanism:GlowPlasticBlock>;
val ingot = <Mekanism:Ingot>;
val mekItemProxy = <Mekanism:ItemProxy>;
val jetpack = <Mekanism:Jetpack>;
val enrichmentChamber = <Mekanism:MachineBlock>;
val rotaryCondensentrator = <Mekanism:MachineBlock2>;
val networkReader = <Mekanism:NetworkReader>;
val obsidianTNT = <Mekanism:ObsidianTNT>;
val oreBlock = <Mekanism:OreBlock>;
val cable = <Mekanism:PartTransmitter>;
val plasticBlock = <Mekanism:PlasticBlock>;
val plasticFence = <Mekanism:PlasticFence>;
val hdpePellet = <Mekanism:Polyethene>;
val portableTeleporter = <Mekanism:PortableTeleporter>;
val reinforcedAlloy = <Mekanism:ReinforcedAlloy>;
val reinforcedPlasticBlock = <Mekanism:ReinforcedPlasticBlock>;
val roadPlasticBlock = <Mekanism:RoadPlasticBlock>;
val robit = <Mekanism:Robit>;
val salt = <Mekanism:Salt>;
val saltBlock = <Mekanism:SaltBlock>;
val sawdust = <Mekanism:Sawdust>;
val scubaTank = <Mekanism:ScubaTank>;
val seismicReader = <Mekanism:SeismicReader>;
val oreShard = <Mekanism:Shard>;
val slickPlasticBlock = <Mekanism:SlickPlasticBlock>;
val speedUpgrade = <Mekanism:SpeedUpgrade>;
val substrate = <Mekanism:Substrate>;
val teleportationCore = <Mekanism:TeleportationCore>;
val walkieTalkie = <Mekanism:WalkieTalkie>;
val heatGenerator = <MekanismGenerators:Generator>;
val solarPanel = <MekanismGenerators:SolarPanel>;
val bronzeAxe = <MekanismTools:BronzeAxe>;
val bronzeBoots = <MekanismTools:BronzeBoots>;
val bronzeChestplate = <MekanismTools:BronzeChestplate>;
val bronzeHelmet = <MekanismTools:BronzeHelmet>;
val bronzeHoe = <MekanismTools:BronzeHoe>;
val bronzeLeggings = <MekanismTools:BronzeLeggings> ;
val bronzePaxel = <MekanismTools:BronzePaxel>;
val bronzePick = <MekanismTools:BronzePickaxe>;
val bronzeShovel = <MekanismTools:BronzeShovel>;
val bronzeSword = <MekanismTools:BronzeSword>;
val diamondPaxel = <MekanismTools:DiamondPaxel>;
val glowstoneAxe = <MekanismTools:GlowstoneAxe>;
val glowstoneBoots = <MekanismTools:GlowstoneBoots>;
val glowstoneChestplate = <MekanismTools:GlowstoneChestplate>;
val glowstoneHelmet = <MekanismTools:GlowstoneHelmet>;
val glowstoneHoe = <MekanismTools:GlowstoneHoe>;
val glowstoneLeggings = <MekanismTools:GlowstoneLeggings> ;
val glowstonePaxel = <MekanismTools:GlowstonePaxel>;
val glowstonePick = <MekanismTools:GlowstonePickaxe>;
val glowstoneShovel = <MekanismTools:GlowstoneShovel>;
val glowstoneSword = <MekanismTools:GlowstoneSword>;
val ironPaxel = <MekanismTools:IronPaxel>;
val lapisLazuliAxe = <MekanismTools:LapisLazuliAxe>;
val lapisLazuliBoots = <MekanismTools:LapisLazuliBoots>;
val lapisLazuliChestplate = <MekanismTools:LapisLazuliChestplate>;
val lapisLazuliHelmet = <MekanismTools:LapisLazuliHelmet>;
val lapisLazuliHoe = <MekanismTools:LapisLazuliHoe>;
val lapisLazuliLeggings = <MekanismTools:LapisLazuliLeggings> ;
val lapisLazuliPaxel = <MekanismTools:LapisLazuliPaxel>;
val lapisLazuliPick = <MekanismTools:LapisLazuliPickaxe>;
val lapisLazuliShovel = <MekanismTools:LapisLazuliShovel>;
val lapisLazuliSword = <MekanismTools:LapisLazuliSword>;
val obsidianAxe = <MekanismTools:ObsidianAxe>;
val obsidianBoots = <MekanismTools:ObsidianBoots>;
val obsidianChestplate = <MekanismTools:ObsidianChestplate>;
val obsidianHelmet = <MekanismTools:ObsidianHelmet>;
val obsidianHoe = <MekanismTools:ObsidianHoe>;
val obsidianLeggings = <MekanismTools:ObsidianLeggings> ;
val obsidianPaxel = <MekanismTools:ObsidianPaxel>;
val obsidianPick = <MekanismTools:ObsidianPickaxe>;
val obsidianShovel = <MekanismTools:ObsidianShovel>;
val obsidianSword = <MekanismTools:ObsidianSword>;
val osmiumAxe = <MekanismTools:OsmiumAxe>;
val osmiumBoots = <MekanismTools:OsmiumBoots>;
val osmiumChestplate = <MekanismTools:OsmiumChestplate>;
val osmiumHelmet = <MekanismTools:OsmiumHelmet>;
val osmiumHoe = <MekanismTools:OsmiumHoe>;
val osmiumLeggings = <MekanismTools:OsmiumLeggings> ;
val osmiumPaxel = <MekanismTools:OsmiumPaxel>;
val osmiumPick = <MekanismTools:OsmiumPickaxe>;
val osmiumShovel = <MekanismTools:OsmiumShovel>;
val osmiumSword = <MekanismTools:OsmiumSword>;
val steelAxe = <MekanismTools:SteelAxe>;
val steelBoots = <MekanismTools:SteelBoots>;
val steelChestplate = <MekanismTools:SteelChestplate>;
val steelHelmet = <MekanismTools:SteelHelmet>;
val steelHoe = <MekanismTools:SteelHoe>;
val steelLeggings = <MekanismTools:SteelLeggings> ;
val steelPaxel = <MekanismTools:SteelPaxel>;
val steelPick = <MekanismTools:SteelPickaxe>;
val steelShovel = <MekanismTools:SteelShovel>;
val steelSword = <MekanismTools:SteelSword>;
val stonePaxel = <MekanismTools:StonePaxel>;
val woodPaxel = <MekanismTools:WoodPaxel>;

##Minecraft
val lever = <minecraft:lever>;
val glass = <minecraft:glass>;
val ironIngot = <minecraft:iron_ingot>;
val compass = <minecraft:compass>;
val woodPlankAll = <minecraft:planks:*>;
val woolAll = <minecraft:wool:*>;
val logAll = <minecraft:log:*>;

##Recipes
recipes.remove(shipHelm);
recipes.remove(floater);
recipes.remove(allArcBalloons);
recipes.remove(gaugeBasic);
recipes.remove(gaugeAdvanced);
recipes.remove(bufferShore);
recipes.remove(engineSteam);

recipes.addShaped(shipHelm, [[lever, glass, lever], [woodPlank, controlCircuitAdv, woodPlank], [woodPlank, woodPlank, woodPlank]]);
recipes.addShaped(gaugeBasic, [[glass, compass, glass], [ingotIron, controlCircuitAdv, ingotIron], [ingotIron, ingotIron, ingotIron]]);
recipes.addShaped(gaugeAdvanced, [[null, compass, null], [controlCircuit, gaugeBasic, controlCircuit], [null, null, null]]);
recipes.addShaped(engineSteam, [[ironIngot, cableAll, ironIngot], [ironIngot, heatGenerator, ironIngot], [ironIngot, ironIngot, ironIngot]]);
recipes.addShaped(arcBalloonWhite, [[woolAll, woolAll, woolAll], [woolAll,mekBalloonWhite, woolAll], [woolAll, woolAll, woolAll]]);
recipes.addShaped(arcBalloonOrange, [[woolAll, woolAll, woolAll], [woolAll,mekBalloonOrange, woolAll], [woolAll, woolAll, woolAll]]);
recipes.addShaped(arcBalloonMagenta, [[woolAll, woolAll, woolAll], [woolAll,mekBalloonMagenta, woolAll], [woolAll, woolAll, woolAll]]);
recipes.addShaped(arcBalloonBlueLight, [[woolAll, woolAll, woolAll], [woolAll,mekBalloonBlueLight, woolAll], [woolAll, woolAll, woolAll]]);
recipes.addShaped(arcBalloonYellow, [[woolAll, woolAll, woolAll], [woolAll,mekBalloonYellow, woolAll], [woolAll, woolAll, woolAll]]);
recipes.addShaped(arcBalloonLime, [[woolAll, woolAll, woolAll], [woolAll,mekBalloonLime, woolAll], [woolAll, woolAll, woolAll]]);
recipes.addShaped(arcBalloonPink, [[woolAll, woolAll, woolAll], [woolAll,mekBalloonPink, woolAll], [woolAll, woolAll, woolAll]]);
recipes.addShaped(arcBalloonGray, [[woolAll, woolAll, woolAll], [woolAll,mekBalloonGrey, woolAll], [woolAll, woolAll, woolAll]]);
recipes.addShaped(arcBalloonSilver, [[woolAll, woolAll, woolAll], [woolAll,mekBalloonGreyLight, woolAll], [woolAll, woolAll, woolAll]]);
recipes.addShaped(arcBalloonCyan, [[woolAll, woolAll, woolAll], [woolAll,mekBalloonCyan, woolAll], [woolAll, woolAll, woolAll]]);
recipes.addShaped(arcBalloonPurple, [[woolAll, woolAll, woolAll], [woolAll,mekBalloonPurple, woolAll], [woolAll, woolAll, woolAll]]);
recipes.addShaped(arcBalloonBlue, [[woolAll, woolAll, woolAll], [woolAll,mekBalloonBlue, woolAll], [woolAll, woolAll, woolAll]]);
recipes.addShaped(arcBalloonBrown, [[woolAll, woolAll, woolAll], [woolAll,mekBalloonBrown, woolAll], [woolAll, woolAll, woolAll]]);
recipes.addShaped(arcBalloonGreen, [[woolAll, woolAll, woolAll], [woolAll,mekBalloonGreen, woolAll], [woolAll, woolAll, woolAll]]);
recipes.addShaped(arcBalloonRed, [[woolAll, woolAll, woolAll], [woolAll,mekBalloonRed, woolAll], [woolAll, woolAll, woolAll]]);
recipes.addShaped(arcBalloonBlack, [[woolAll, woolAll, woolAll], [woolAll,mekBalloonBlack, woolAll], [woolAll, woolAll, woolAll]]);
recipes.addShaped(bufferShore * 2, [[null, null, null], [allBalloons, woodPlankAll, allBalloons], [null, null, null]]);
recipes.addShaped(floater * 2, [[null, allBalloons, null], [null, logAll, null], [null, allBalloons, null]]);

//Must remain here.
print("ArchS-Mek Script Loaded.");
